version: '2.4'

services:
  database:
    image: 'mysql:latest'
    container_name: mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: oneshot
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: 'redis:latest'
    container_name: redis-container
    ports:
      - '6379:6379'

  elasticsearch:
    image: 'elasticsearch:8.15.1'
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # 보안 비활성화 (테스트용)
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    command: >
      bash -c "if [ ! -f /usr/share/elasticsearch/plugins/analysis-nori/plugin-descriptor.properties ]; then
      elasticsearch-plugin install --batch analysis-nori; fi && /usr/local/bin/docker-entrypoint.sh"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  kibana:
    image: 'kibana:8.15.1'
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  cerebro:
    image: yannart/cerebro
    container_name: cerebro
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq-container
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    image: oneshot:latest
    container_name: oneshot-app
    env_file:
      - .env
    restart: always
    environment:
      #
      PAYMENT_SECRETKEY: ${PAYMENT_SECRET_KEY}
      #
      # ////////////////
      # //    Prod    //
      # ////////////////
      #
      # SQL
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/oneshot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      # ElasticSearch
      SPRING_ELASTICSEARCH_URIS: ${ELASTICSEARCH_HOST}
      # S3
      CLOUD_AWS_CREDENTIALS_ACCESSKEY: ${AWS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRETKEY: ${AWS_SECRET_KEY}
      CLOUD_AWS_S3_BUCKETNAME: oneshot-bucket2
      #
      # ////////////////
      # //  Security  //
      # ////////////////
      #
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      #
      SUPER_USERNAME: ${SUPER_USERNAME}
      SUPER_NICKNAME: ${SUPER_NICKNAME}
      SUPER_PASSWORD: ${SUPER_PASSWORD}
      #
      # NAVER
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID: ${OAUTH2_NAVER_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET: ${OAUTH2_NAVER_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI: "{baseUrl}/login/oauth2/code/naver"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_AUTHORIZATION_GRANT_TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_NAME: Naver
      #
      # GOOGLE
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${OAUTH2_GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${OAUTH2_GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "{baseUrl}/login/oauth2/code/google"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: profile
      #
      # NAVER Provider
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_AUTHORIZATION_URI: https://nid.naver.com/oauth2.0/authorize
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_TOKEN_URI: https://nid.naver.com/oauth2.0/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_USER_INFO_URI: https://openapi.naver.com/v1/nid/me
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_USER_NAME_ATTRIBUTE: response
    depends_on:
        elasticsearch:
          condition: service_healthy
        database:
          condition: service_started
        redis:
          condition: service_started
        rabbitmq:
          condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005"


volumes:
  mysql_data:
  esdata:
  rabbitmq_data: