services:
  app:
    build: .
    image: ${DOCKERHUB_USERNAME}/oneshot:latest
    container_name: oneshot-app
#    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/oneshot
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      # 확인!!
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
      #
      SPRING_DATA_REDIS_HOST: oneshot-redis-78f1xs.serverless.apn2.cache.amazonaws.com
      SPRING_DATA_REDIS_PORT: 6379
      #
      SPRING_PROFILES_ACTIVE: prod
      #
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      #
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${AWS_SECRET_KEY}
      CLOUD_AWS_S3_BUCKET_NAME: oneshot-bucket2
      OPENSEARCH_HOST: vpc-oneshot-elasticsearch-qm3januchy4i3zzbovj3hdwneq.ap-northeast-2.es.amazonaws.com
      OPENSEARCH_PORT: 9200
      #
      SUPER_USERNAME: ${SUPER_USERNAME}
      SUPER_NICKNAME: ${SUPER_NICKNAME}
      SUPER_PASSWORD: ${SUPER_PASSWORD}
      # NAVER
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID: ${OAUTH2_NAVER_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET: ${OAUTH2_NAVER_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI: "{baseUrl}/login/oauth2/code/naver"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_AUTHORIZATION_GRANT_TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_NAME: Naver
      # GOOGLE
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${OAUTH2_GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${OAUTH2_GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "{baseUrl}/login/oauth2/code/google"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: profile
      # NAVER Provider
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_AUTHORIZATION_URI: https://nid.naver.com/oauth2.0/authorize
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_TOKEN_URI: https://nid.naver.com/oauth2.0/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_USER_INFO_URI: https://openapi.naver.com/v1/nid/me
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_USER_NAME_ATTRIBUTE: response
    ports:
      - "8080:8080"