services:
  database:
    image: 'mysql:latest'
    container_name: mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: oneshot
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: 'redis:latest'
    container_name: redis-container
    ports:
      - '6379:6379'

  app:
    build: .
    container_name: oneshot-app
    env_file:
      - .env
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/oneshot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - database
      - redis
    ports:
      - "8080:8080"

volumes:
  mysql_data: