
== AddressController

== 주소 생성
=== 주소 생성 성공
operation::address-controller-test/success-create-address[snippets="http-request,http-response"]

== 주소 조회
=== 주소 목록 조회 성공
operation::address-controller-test/success-get-addresses[snippets="http-request,http-response"]
=== 주소 목록 조회 성공: 빈 목록 반환(등록된 주소가 없는 경우)
operation::address-controller-test/success-get-addresses-empty-list[snippets="http-request,http-response"]
=== 주소 목록 조회 성공: 첫 페이지 주소 목록 조회
operation::address-controller-test/success-get-addresses-first-page[snippets="http-request,http-response"]
=== 주소 단건 조회 성공
operation::address-controller-test/success-get-address[snippets="http-request,http-response"]
=== 주소 단건 조회 실패: 존재하지 않는 주소로 조회 시도
operation::address-controller-test/invalid-address-id-get-address[snippets="http-request,http-response"]

== 주소 수정
=== 주소 수정 성공
operation::address-controller-test/success-update-address[snippets="http-request,http-response"]
=== 주소 수정 실패: 디폴트주소인 주소의 기본값 여부를 False로 변경 시도
operation::address-controller-test/invalid-default-update-address[snippets="http-request,http-response"]
=== 주소 수정 실패: 존재하지 않는 주소로 수정 시도
operation::address-controller-test/invalid-address-id-update-address[snippets="http-request,http-response"]

== 주소 삭제
=== 주소 삭제 성공
operation::address-controller-test/success-address-delete[snippets="http-request,http-response"]
=== 주소 삭제 실패: 디폴트주소 삭제 시도
operation::address-controller-test/invalid-default-delete-address[snippets="http-request,http-response"]
=== 주소 삭제 실패: 존재하지 않는 주소로 조회 시도
operation::address-controller-test/invalid-address-id-delete-address[snippets="http-request,http-response"]


