== CouponController

=== 유저쿠폰 사용 성공
operation::coupon-controller-test/success-use-user-coupon[snippets="http-request,http-response"]
=== 유저쿠폰 사용 실패: 존재하지 않는 유저 쿠폰 아이디로 사용 시도
operation::coupon-controller-test/invalid-user-coupon-id-use-user-coupon[snippets="http-request,http-response"]
=== 쿠몬 목록 조회 성공
operation::coupon-controller-test/success-get-coupons[snippets="http-request,http-response"]
=== 쿠폰 목록 조회 성공: 빈 목록 조회
operation::coupon-controller-test/success-get-empty-coupons[snippets="http-request,http-response"]
=== 쿠폰 단건 조회 성공
operation::coupon-controller-test/success-get-coupon[snippets="http-request,http-response"]
=== 쿠폰 단건 조회 실패: 존재하지 않는 쿠폰 아이디로 조회 시도
operation::coupon-controller-test/invalid-coupon-id-get-coupon[snippets="http-request,http-response"]
=== 유저쿠폰 목록 조회 성공
operation::coupon-controller-test/success-get-user-coupons[snippets="http-request,http-response"]
=== 유저쿠폰 목록 조회 성공: 빈 목록 조회
operation::coupon-controller-test/success-get-empty-user-coupons[nippets="http-request,http-response"]
=== 유저쿠폰 단건 조회 성공
operation::coupon-controller-test/success-get-user-coupon[snippets="http-request,http-response"]
=== 유저쿠폰 단건 조회 실패: 존재하지 않는 유저쿠폰 아이디로 조회 시도
operation::coupon-controller-test/invalid-user-coupon-id-get-user-coupon[snippets="http-request,http-response"]
