== FavoriteController

=== 즐겨찾기 등록 성공
operation::favorite-controller-test/success-create-favorite[snippets="http-request,http-response"]
=== 즐겨찾기 등록 실패: 이미 등록된 즐겨찾기
operation::favorite-controller-test/duplicated-favorite-create-favorite[snippets="http-request,http-response"]
=== 즐겨찾기 등록 실패: 존재하지 않는 칵테일 아이디로 등록 시도
operation::favorite-controller-test/invalid-favorite-id-create-favorite[snippets="http-request,http-response"]
=== 즐겨찾기 여부 조회 성공
operation::favorite-controller-test/success-check-favorite[snippets="http-request,http-response"]
=== 즐겨찾기 목록 조회 성공
operation::favorite-controller-test/success-get-favorites[snippets="http-request,http-response"]
=== 즐겨찾기 목록 조회 성공: 빈 목록 조회
operation::favorite-controller-test/success-get-empty-favorites[snippets="http-request,http-response"]
=== 즐겨찾기 삭제 성공
operation::favorite-controller-test/success-delete-favorite[snippets="http-request,http-response"]
=== 즐겨찾기 삭제 실패: 존재하지 않는 즐겨찾기아이디로 삭제 시도
operation::favorite-controller-test/invalid-id-delete-favorite[snippets="http-request,http-response"]
