name: Gradle Build

on:
  push:
    branches: [ "main", "develop_v1" ]
  pull_request:
    branches: [ "main", "develop_v1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Gradle build
        run: |
          chmod +x gradlew
          ./gradlew clean build --no-daemon -x test