name: Gradle Build

on:
  push:
    branches: [ "develop_v1", "develop_v2" ]
  pull_request:
    branches: [ "develop_v1", "develop_v2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle build
        run: ./gradlew clean build --no-daemon