name: Gradle Build

on:
  push:
    branches: [ "main", "develop_v1" ]
  pull_request:
    branches: [ "main", "develop_v1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle build
        run: |
          chmod +x gradlew
          ./gradlew clean build --no-daemon -x test

      - name: Log in to Docker Hub
        if: contains(github.ref, 'main')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        if: contains(github.ref, 'main')
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        if: contains(github.ref, 'main')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/oneshot:latest

      - name: Copy file to prod
        if: contains(github.ref, 'main')
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          password: ${{ secrets.PRIVATE_KEY }}
#          port:
          source: "./docker-compose-prod.yaml"
          target: "~"

      - name: Deploy to prod
        if: contains(github.ref, 'main')
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker ps
            docker-compose down
            docker pull ${{ secrets.DOCKER_USERNAME }}/scheduler:latest
            docker-compose -d -f docker-compose-prod.yml up
            docker image prune -f
